### ISSUE TITLE
Im sorry Im not sure how to make this not and issue or someting so please forgive me 

### ISSUE THREAD

**Issue by ghost** [f4rber/WEBDorker#1]
Just want to say thanks for all the amazing tools your dropping !

Especially some are advanced but you made it easy for somebody to understand when they dont have all the knowledge that sometimes is required for Scrips and Apps etc..

So please Keep up the amazing work and hope people show you the respect and thanks that you truly deserve i  cant wait to see whats Coming Next  <3 !

ill be lurking from the darkness ^-^

**Comment by ghost** [comment]
Again i apologize for not understanding how to make this NOT AN issue !

**Comment by f4rber** [comment]
Thank you for your support, mate! ;)
